language: node_js
name: "smart contract tests"
node_js:
  - "10"
before_install:
  - rm -rf build
  - rm -rf node_modules
  - npm install -g npm@6.13
  - npm install -g ganache-cli
before_script:
  - ganache-cli -d --gasLimit=100000000 -i 100001  > /dev/null &
  - npm ci
script:
  - npm run coverage && cat ./coverage/lcov.info | coveralls
